version: '3'
services:
  app:
    restart: always
    env_file: .env
    image: mvkaran/django-dashboard-adminator:app-1.0
    networks:
      - web_network
  nginx:
    restart: always
    image: mvkaran/django-dashboard-adminator:nginx-1.0
    ports:
      - "80:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - app
networks:
  web_network:
    driver: bridge
