version: '3'
services:
  app:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile-app
    image: mvkaran/django-dashboard-adminator:app-v2
    ports:
      - "5005:5005"
    networks:
      - web_network
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: mvkaran/django-dashboard-adminator:nginx-v2
    ports:
      - "80:85"
    networks:
      - web_network
    depends_on: 
      - app
networks:
  web_network:
    driver: bridge
