FROM python:3.6-slim

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY manage.py gunicorn-cfg.py db.sqlite3 .env ./
COPY app app
COPY authentication authentication
COPY core core

RUN python manage.py makemigrations && python manage.py migrate

EXPOSE 5005
CMD ["gunicorn", "--config", "gunicorn-cfg.py", "core.wsgi"]