name: CI/CD
on:
  push:
    branches: [ master ]


jobs:
  
  build:
   
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build and push Docker image for App
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mvkaran/django-dashboard-adminator
        path: . 
        dockerfile:  Dockerfile-app
        tags: app-latest 
        tag_with_ref: true
        tag_with_sha: true
        
    - name: Build and push Docker image for Nginx
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mvkaran/django-dashboard-adminator
        path: . 
        dockerfile:  Dockerfile-nginx
        tags: nginx-latest 
        tag_with_ref: true
        tag_with_sha: true

  provision-deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./aws-terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./aws-terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./aws-terraform

      